# LangChain Supported Languages
# https://python.langchain.com/api_reference/text_splitters/base/langchain_text_splitters.base.Language.html
cpp: '.cpp'
go: '.go'
java: '.java'
kotlin: '.kt'
js: '.js'
ts: '.ts'
php: '.php'
proto: '.proto'
python: '.py'
rst: '.rst'
ruby: '.rb'
rust: '.rs'
scala: '.scala'
swift: '.swift'
markdown: '.md'
latex: '.tex'
html: '.html'
sol: '.sol'
csharp: '.cs'
cobol: '.cobol'
c: '.c'
lua: '.lua'
perl: '.pl'
haskell: '.hs'
plaintext: ''